sudo: required
services:
  -docker

  before_install:
    -docker build -t multidocker/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true multidocker/react-test npm test

after_success:
  - docker build -t multidocker/client ./client
  - docker build -t multidocker/nginx ./nginx
  - docker build -t multidocker/server ./server
  - docker build -t multidocker/worker ./worker 
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push multidocker/client
  - docker push multidocker/nginx
  - docker push multidocker/server
  - docker push multidocker/worker